[package]
name = "lab_manager"
version = "0.1.0"
edition = "2021"

[lib]
name = "lab_manager"
path = "src/lib.rs"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.36", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
postgres = { version = "0.19", features = ["with-uuid-1", "with-chrono-0_4"] }

# Authentication
jsonwebtoken = "9.2"
saml2 = "0.3"
quick-xml = "0.31"
reqwest = { version = "0.11", features = ["json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Async runtime
futures = "0.3"

[dev-dependencies]
tokio-test = "0.4"
